/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["HealthController_getHealth_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations */
        get: operations["OrganizationController_findAll_v1"];
        put?: never;
        /** Create a new organization */
        post: operations["OrganizationController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization by ID */
        get: operations["OrganizationController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete an organization (ADMIN only) */
        delete: operations["OrganizationController_delete_v1"];
        options?: never;
        head?: never;
        /** Update an organization (STAFF or ADMIN only) */
        patch: operations["OrganizationController_update_v1"];
        trace?: never;
    };
    "/v1/organizations/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join an organization as MEMBER */
        post: operations["OrganizationController_join_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave an organization */
        post: operations["OrganizationController_leave_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user information */
        get: operations["UserController_getCurrentUser_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user organization memberships */
        get: operations["UserController_getMemberships_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["UserController_getProfile_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: operations["UserController_updateProfile_v1"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Overall health status of the service
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Format: date-time
             * @description ISO timestamp when the health check was performed
             * @example 2025-12-24T22:00:00.000Z
             */
            timestamp: string;
            /**
             * @description Database connection status
             * @example up
             * @enum {string}
             */
            database: "up" | "error";
        };
        CreateOrganizationDto: {
            /**
             * @description Organization name
             * @example Acme Corp
             */
            name: string;
        };
        OrganizationResponseDto: {
            /**
             * @description Organization ID
             * @example clr1abc2d0000
             */
            id: string;
            /**
             * @description Organization name
             * @example Acme Corp
             */
            name?: Record<string, never>;
            /**
             * @description Number of members
             * @example 5
             */
            memberCount: number;
            /**
             * Format: date-time
             * @description Created timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Updated timestamp
             */
            updatedAt: string;
        };
        ErrorResponseDto: {
            /**
             * @description HTTP status code
             * @example 400
             */
            statusCode: number;
            /**
             * @description Error type/code
             * @example BAD_REQUEST
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid request parameters
             */
            message: string;
            /**
             * @description Detailed validation errors or additional context
             * @example [
             *       "field must be a string",
             *       "value is required"
             *     ]
             */
            details?: string[];
            /**
             * @description Request path that caused the error
             * @example /v1/resource/abc123
             */
            path?: string;
            /**
             * @description Timestamp when the error occurred
             * @example 2025-12-26T12:00:00.000Z
             */
            timestamp?: string;
        };
        PaginationMetaDto: {
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Items per page
             * @example 20
             */
            per_page: number;
            /**
             * @description Total number of items
             * @example 100
             */
            total: number;
            /**
             * @description Total number of pages
             * @example 5
             */
            total_pages: number;
        };
        PaginatedOrganizationResponseDto: {
            data: components["schemas"]["OrganizationResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        UpdateOrganizationDto: {
            /**
             * @description Organization name
             * @example Acme Corp
             */
            name?: string;
        };
        OrganizationMemberResponseDto: {
            /** @description Membership ID */
            id: string;
            /** @description User ID */
            userId: string;
            /** @description Organization ID */
            organizationId: string;
            /**
             * @description Member role
             * @enum {string}
             */
            role: "MEMBER" | "STAFF" | "ADMIN";
            /**
             * Format: date-time
             * @description Joined timestamp
             */
            createdAt: string;
        };
        UserResponseDto: {
            /**
             * @description User subject identifier from the identity provider
             * @example auth0|507f1f77bcf86cd799439011
             */
            sub: string;
            /**
             * @description Username or preferred username
             * @example john.doe
             */
            username?: string;
            /**
             * @description Full name of the user
             * @example John Doe
             */
            name?: string;
            /**
             * Format: email
             * @description Email address of the user
             * @example john.doe@example.com
             */
            email?: string;
            /**
             * @description List of user scopes/permissions
             * @example [
             *       "read",
             *       "write"
             *     ]
             */
            scopes: Record<string, never>[][];
        };
        UserMembershipResponseDto: {
            /**
             * @description Membership ID
             * @example clr1abc2d0000
             */
            id: string;
            /**
             * @description Organization ID
             * @example clr1abc2d0001
             */
            organizationId: string;
            /**
             * @description Organization name
             * @example Acme Corp
             */
            organizationName?: Record<string, never>;
            /**
             * @description Member role
             * @example MEMBER
             * @enum {string}
             */
            role: "MEMBER" | "STAFF" | "ADMIN";
            /**
             * Format: date-time
             * @description Joined timestamp
             */
            joinedAt: string;
        };
        UserProfilePictureDto: {
            id: string;
            url: string;
            alt?: string;
            isPrimary: boolean;
        };
        UserProfileResponseDto: {
            userId: string;
            bio?: string;
            favoriteSports: string[];
            pictures: components["schemas"]["UserProfilePictureDto"][];
        };
        UpdateUserProfileDto: {
            bio?: string;
            favoriteSports?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    OrganizationController_findAll_v1: {
        parameters: {
            query?: {
                per_page?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrganizationResponseDto"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrganizationController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrganizationController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrganizationController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Insufficient role — requires ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrganizationController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Insufficient role — requires STAFF or ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrganizationController_join_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMemberResponseDto"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Already a member */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrganizationController_leave_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Left the organization */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not a member of this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserController_getCurrentUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserController_getMemberships_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMembershipResponseDto"][];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserController_getProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponseDto"];
                };
            };
        };
    };
    UserController_updateProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponseDto"];
                };
            };
        };
    };
}
